export const AllWeb = [
  {
    id: 1,
    name: "2Kea-Studio",
    kind: "Funiture Shop",
    team: "Team Project",
    info: "dd",
    img: dsdd,
    responsiveimg: dsdd,
    link: "",
  },
  {
    id: 2,
    name: "costing",
    kind: "Glasses Shop",
    team: "Solo Project",
    info: "dd",
    img: dsdd,
    responsiveimg: dsdd,
    link: "",
  },
  {
    id: 3,
    name: "TacoBell",
    kind: "Taco Shop",
    team: "Solo Project",
    info: "dd",
    img: dsdd,
    responsiveimg: dsdd,
    link: "",
  },
  {
    id: 4,
    name: "국가유산청",
    kind: "Funiture Shop",
    team: "Solo Project",
    info: "dd",
    img: dsdd,
    responsiveimg: dsdd,
    link: "",
  },
  {
    id: 5,
    name: "ToDo List",
    kind: "Funiture Shop",
    team: "Team Project",
    info: "dd",
    img: dsdd,
    responsiveimg: dsdd,
    link: "",
  },
];
